package review

import "time"

// ReviewStatus tracks the lifecycle of a review through the controlled workflow.
type ReviewStatus string

const (
	// StatusCreated means the request was accepted and a review_id was assigned.
	StatusCreated ReviewStatus = "CREATED"
	// StatusNormalized means the external request has been mapped into internal form.
	StatusNormalized ReviewStatus = "NORMALIZED"
	// StatusUnderstood means semantic interpretation of the change is complete.
	StatusUnderstood ReviewStatus = "UNDERSTOOD"
	// StatusCollectingContext means evidence retrieval is in progress.
	StatusCollectingContext ReviewStatus = "COLLECTING_CONTEXT"
	// StatusContextReady means the current evidence set is ready for downstream logic.
	StatusContextReady ReviewStatus = "CONTEXT_READY"
	// StatusSignalsExtracted means risk signals were derived from change and evidence.
	StatusSignalsExtracted ReviewStatus = "SIGNALS_EXTRACTED"
	// StatusScored means the review has a computed risk score and level.
	StatusScored ReviewStatus = "SCORED"
	// StatusRecommended means recommendation and rollback output were generated.
	StatusRecommended ReviewStatus = "RECOMMENDED"
	// StatusWaitingHumanReview means automated flow stopped for explicit human action.
	StatusWaitingHumanReview ReviewStatus = "WAITING_HUMAN_REVIEW"
	StatusApproved           ReviewStatus = "APPROVED"
	StatusRejected           ReviewStatus = "REJECTED"
	StatusOverridden         ReviewStatus = "OVERRIDDEN"
	StatusFailed             ReviewStatus = "FAILED"
	StatusCancelled          ReviewStatus = "CANCELLED"
)

// RiskLevel is the coarse-grained severity bucket used by the API and policies.
type RiskLevel string

const (
	RiskLow      RiskLevel = "LOW"
	RiskMedium   RiskLevel = "MEDIUM"
	RiskHigh     RiskLevel = "HIGH"
	RiskCritical RiskLevel = "CRITICAL"
)

// CreateReviewRequest is the external API payload for starting a review.
type CreateReviewRequest struct {
	SourceType  string        `json:"source_type"`
	SourceID    string        `json:"source_id"`
	Repo        string        `json:"repo,omitempty"`
	Service     string        `json:"service,omitempty"`
	Environment string        `json:"environment"`
	TriggerMode string        `json:"trigger_mode,omitempty"`
	DedupeKey   string        `json:"dedupe_key,omitempty"`
	TriggeredBy string        `json:"triggered_by,omitempty"`
	Payload     ReviewPayload `json:"payload"`
}

// ReviewPayload keeps the source-specific metadata that the MVP currently needs.
type ReviewPayload struct {
	Title      string         `json:"title,omitempty"`
	Author     string         `json:"author,omitempty"`
	BaseCommit string         `json:"base_commit,omitempty"`
	HeadCommit string         `json:"head_commit,omitempty"`
	DiffURL    string         `json:"diff_url,omitempty"`
	Metadata   map[string]any `json:"metadata,omitempty"`
}

// CreateReviewResponse is returned immediately after a review is accepted.
type CreateReviewResponse struct {
	ReviewID string       `json:"review_id"`
	TaskID   string       `json:"task_id"`
	Status   ReviewStatus `json:"status"`
	PollURL  string       `json:"poll_url"`
}

// Review is the top-level materialized summary exposed by the API.
type Review struct {
	ReviewID            string       `json:"review_id"`
	ChangeID            string       `json:"change_id,omitempty"`
	DedupeKey           string       `json:"-"`
	SourceType          string       `json:"source_type"`
	Repo                string       `json:"repo,omitempty"`
	Service             string       `json:"service,omitempty"`
	Environment         string       `json:"environment,omitempty"`
	Status              ReviewStatus `json:"status"`
	RiskLevel           RiskLevel    `json:"risk_level,omitempty"`
	Score               int          `json:"score,omitempty"`
	Confidence          float64      `json:"confidence,omitempty"`
	Summary             string       `json:"summary,omitempty"`
	HumanReviewRequired bool         `json:"human_review_required"`
	CreatedAt           time.Time    `json:"created_at"`
	UpdatedAt           time.Time    `json:"updated_at"`
}

// RiskSignal describes one concrete reason why a change is considered risky.
type RiskSignal struct {
	SignalID     string    `json:"signal_id,omitempty"`
	SignalName   string    `json:"signal_name"`
	Severity     RiskLevel `json:"severity"`
	ScoreDelta   int       `json:"score_delta,omitempty"`
	Explanation  string    `json:"explanation,omitempty"`
	EvidenceRefs []string  `json:"evidence_refs,omitempty"`
}

// Recommendation captures the actionable release guidance generated by the system.
type Recommendation struct {
	RequiredReviewers []string        `json:"required_reviewers,omitempty"`
	ReleaseWindow     string          `json:"release_window,omitempty"`
	RolloutStrategy   RolloutStrategy `json:"rollout_strategy,omitempty"`
	ObservabilityPlan []string        `json:"observability_plan,omitempty"`
}

// RolloutStrategy is the release progression plan attached to a recommendation.
type RolloutStrategy struct {
	Steps           []string `json:"steps,omitempty"`
	IntervalMinutes int      `json:"interval_minutes,omitempty"`
}

// RollbackPlan captures the minimum structured rollback guidance for the review.
type RollbackPlan struct {
	TriggerCondition       string   `json:"trigger_condition,omitempty"`
	Steps                  []string `json:"steps,omitempty"`
	VersionToRestore       string   `json:"version_to_restore,omitempty"`
	VerificationMetrics    []string `json:"verification_metrics,omitempty"`
	RollbackDeadlineSecond int      `json:"rollback_deadline_seconds,omitempty"`
}

// EvidenceItem is one unit of supporting evidence attached to the review result.
type EvidenceItem struct {
	EvidenceID     string         `json:"evidence_id"`
	Type           string         `json:"type"`
	Source         string         `json:"source"`
	Title          string         `json:"title,omitempty"`
	ContentSnippet string         `json:"content_snippet,omitempty"`
	ReferenceURL   string         `json:"reference_url,omitempty"`
	Confidence     float64        `json:"confidence,omitempty"`
	Metadata       map[string]any `json:"metadata,omitempty"`
}

// GetReviewResponse is the aggregate response returned by GET /reviews/{id}.
type GetReviewResponse struct {
	Review         Review         `json:"review"`
	Signals        []RiskSignal   `json:"signals,omitempty"`
	Recommendation Recommendation `json:"recommendation,omitempty"`
	RollbackPlan   RollbackPlan   `json:"rollback_plan,omitempty"`
	Evidence       []EvidenceItem `json:"evidence,omitempty"`
}

// TimelineEvent records one state transition or notable review event.
type TimelineEvent struct {
	State  ReviewStatus `json:"state"`
	At     time.Time    `json:"at"`
	Detail string       `json:"detail,omitempty"`
}

// TimelineResponse returns the ordered event history for a review.
type TimelineResponse struct {
	ReviewID string          `json:"review_id"`
	Events   []TimelineEvent `json:"events"`
}

// HumanDecisionRequest is the API payload for explicit human intervention.
type HumanDecisionRequest struct {
	Reviewer string `json:"reviewer"`
	Decision string `json:"decision"`
	Reason   string `json:"reason,omitempty"`
	Notify   bool   `json:"notify,omitempty"`
}

// HumanDecisionResponse acknowledges that a human decision was persisted.
type HumanDecisionResponse struct {
	ReviewID string       `json:"review_id"`
	Status   ReviewStatus `json:"status"`
	Recorded bool         `json:"recorded"`
}

// HumanDecision is the stored representation of a reviewer action.
type HumanDecision struct {
	Reviewer     string    `json:"reviewer"`
	Decision     string    `json:"decision"`
	Reason       string    `json:"reason,omitempty"`
	OverrideFlag bool      `json:"override_flag"`
	CreatedAt    time.Time `json:"created_at"`
}

// RetryRequest captures optional context for a retry.
type RetryRequest struct {
	Reason string `json:"reason,omitempty"`
}

// RetryResponse returns the reused identifiers after a retry is accepted.
type RetryResponse struct {
	ReviewID string       `json:"review_id"`
	TaskID   string       `json:"task_id"`
	Status   ReviewStatus `json:"status"`
}

// EvaluationUpdateRequest carries post-release outcome data back into the system.
type EvaluationUpdateRequest struct {
	ReleaseOutcome  string         `json:"release_outcome,omitempty"`
	IncidentFlag    *bool          `json:"incident_flag,omitempty"`
	OutcomeMetadata map[string]any `json:"outcome_metadata,omitempty"`
}

// EvaluationUpdateResponse confirms evaluation feedback persistence.
type EvaluationUpdateResponse struct {
	ReviewID string `json:"review_id"`
	Recorded bool   `json:"recorded"`
}

// EvaluationMetricsResponse is the coarse aggregate metrics view used by the MVP.
type EvaluationMetricsResponse struct {
	Window  MetricsWindow `json:"window"`
	Service string        `json:"service,omitempty"`
	Metrics Metrics       `json:"metrics"`
}

// MetricsWindow defines the query range for evaluation metrics.
type MetricsWindow struct {
	From string `json:"from"`
	To   string `json:"to"`
}

// Metrics contains simple aggregated indicators over a review population.
type Metrics struct {
	ReviewCount       int     `json:"review_count"`
	HighRiskRecall    float64 `json:"high_risk_recall"`
	FalsePositiveRate float64 `json:"false_positive_rate"`
	OverrideRate      float64 `json:"override_rate"`
	P95LatencyMS      int     `json:"p95_latency_ms"`
}

// EvaluationRecord stores post-review ground-truth style feedback.
type EvaluationRecord struct {
	FinalHumanDecision *string        `json:"final_human_decision,omitempty"`
	ReleaseOutcome     *string        `json:"release_outcome,omitempty"`
	IncidentFlag       *bool          `json:"incident_flag,omitempty"`
	OutcomeMetadata    map[string]any `json:"outcome_metadata,omitempty"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

// ErrorResponse is the common JSON error envelope for the HTTP API.
type ErrorResponse struct {
	Code      string `json:"code"`
	Message   string `json:"message"`
	RequestID string `json:"request_id,omitempty"`
}

// Record is the internal persistence aggregate used by Store implementations.
//
// It combines the public review view with workflow snapshots and supporting
// material so the service can fully reconstruct the state of a review.
type Record struct {
	Review         Review
	Request        *CreateReviewRequest
	Bundle         *ChangeBundle
	Understanding  *ChangeUnderstanding
	TaskID         string
	Signals        []RiskSignal
	Recommendation Recommendation
	RollbackPlan   RollbackPlan
	Evidence       []EvidenceItem
	Timeline       []TimelineEvent
	HumanDecisions []HumanDecision
	Evaluation     *EvaluationRecord
	LastError      string
}
