CREATE TABLE IF NOT EXISTS test_tasks (
    task_id TEXT PRIMARY KEY,
    dedupe_key TEXT UNIQUE,
    scenario TEXT NOT NULL,
    input_type TEXT NOT NULL,
    source_id TEXT NOT NULL,
    repo TEXT,
    service TEXT,
    status TEXT NOT NULL,
    overall_status TEXT NOT NULL DEFAULT 'NEEDS_ATTENTION',
    summary TEXT,
    confidence DOUBLE PRECISION NOT NULL DEFAULT 0,
    human_review_required BOOLEAN NOT NULL DEFAULT FALSE,
    input_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    test_points JSONB NOT NULL DEFAULT '[]'::jsonb,
    test_cases JSONB NOT NULL DEFAULT '[]'::jsonb,
    execution_results JSONB NOT NULL DEFAULT '[]'::jsonb,
    assertion_result JSONB NOT NULL DEFAULT '{}'::jsonb,
    failure_analysis JSONB NOT NULL DEFAULT '{}'::jsonb,
    report JSONB NOT NULL DEFAULT '{}'::jsonb,
    timeline JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
